export const teamData = [
    {
      "LeagueID": "00",
      "SeasonID": "22022",
      "TeamID": 1610612743,
      "TeamCity": "Denver",
      "TeamName": "Nuggets",
      "Conference": "West",
      "ConferenceRecord": "34-18",
      "PlayoffRank": 1,
      "ClinchIndicator": " - w",
      "Division": "Northwest",
      "DivisionRecord": "10-6 ",
      "DivisionRank": 1,
      "WINS": 53,
      "LOSSES": 29,
      "WinPCT": 0.646,
      "LeagueRank": 0,
      "Record": "53-29",
      "HOME": "34-7 ",
      "ROAD": "19-22",
      "L10": "5-5  ",
      "Last10Home": "7-3  ",
      "Last10Road": "3-7  ",
      "OT": "3-0  ",
      "ThreePTSOrLess": "7-6  ",
      "TenPTSOrMore": "29-15",
      "LongHomeStreak": 16,
      "strLongHomeStreak": "W 16",
      "LongRoadStreak": -4,
      "strLongRoadStreak": "L 4",
      "LongWinStreak": 9,
      "LongLossStreak": 4,
      "CurrentHomeStreak": 2,
      "strCurrentHomeStreak": "W 2",
      "CurrentRoadStreak": -4,
      "strCurrentRoadStreak": "L 4",
      "CurrentStreak": 1,
      "strCurrentStreak": "W 1",
      "ConferenceGamesBack": 0.0,
      "DivisionGamesBack": 0.0,
      "ClinchedConferenceTitle": 1,
      "ClinchedDivisionTitle": 1,
      "ClinchedPlayoffBirth": 1,
      "EliminatedConference": 0,
      "EliminatedDivision": 0,
      "AheadAtHalf": "33-9 ",
      "BehindAtHalf": "18-20",
      "TiedAtHalf": "2-0  ",
      "AheadAtThird": "41-4 ",
      "BehindAtThird": "10-24",
      "TiedAtThird": "2-1  ",
      "Score100PTS": "51-21",
      "OppScore100PTS": "45-29",
      "OppOver500": "36-18",
      "LeadInFGPCT": "48-8 ",
      "LeadInReb": "39-9 ",
      "FewerTurnovers": "24-7 ",
      "PointsPG": 115.8,
      "OppPointsPG": 112.5,
      "DiffPointsPG": 3.3,
      "vsEast": "19-11",
      "vsAtlantic": "4-6",
      "vsCentral": "7-3",
      "vsSoutheast": "8-2",
      "vsWest": "34-18",
      "vsNorthwest": "10-6",
      "vsPacific": "13-5",
      "vsSouthwest": "11-7",
      "Jan": "12-4",
      "Feb": "9-3",
      "Mar": "7-7",
      "Apr": "2-3",
      "May": null,
      "Jun": null,
      "Jul": null,
      "Aug": null,
      "Sep": null,
      "Oct": "4-3",
      "Nov": "10-4",
      "Dec": "9-5",
      "PreAS": "41-18",
      "PostAS": "12-11"
    },
    {
      "LeagueID": "00",
      "SeasonID": "22022",
      "TeamID": 1610612749,
      "TeamCity": "Milwaukee",
      "TeamName": "Bucks",
      "Conference": "East",
      "ConferenceRecord": "35-17",
      "PlayoffRank": 1,
      "ClinchIndicator": " - e",
      "Division": "Central",
      "DivisionRecord": "11-5 ",
      "DivisionRank": 1,
      "WINS": 58,
      "LOSSES": 24,
      "WinPCT": 0.707,
      "LeagueRank": 0,
      "Record": "58-24",
      "HOME": "32-9 ",
      "ROAD": "26-15",
      "L10": "6-4  ",
      "Last10Home": "6-4  ",
      "Last10Road": "7-3  ",
      "OT": "3-2  ",
      "ThreePTSOrLess": "6-1  ",
      "TenPTSOrMore": "30-15",
      "LongHomeStreak": 11,
      "strLongHomeStreak": "W 11",
      "LongRoadStreak": 9,
      "strLongRoadStreak": "W 9",
      "LongWinStreak": 16,
      "LongLossStreak": 4,
      "CurrentHomeStreak": -1,
      "strCurrentHomeStreak": "L 1",
      "CurrentRoadStreak": -1,
      "strCurrentRoadStreak": "L 1",
      "CurrentStreak": -2,
      "strCurrentStreak": "L 2",
      "ConferenceGamesBack": 0.0,
      "DivisionGamesBack": 0.0,
      "ClinchedConferenceTitle": 1,
      "ClinchedDivisionTitle": 1,
      "ClinchedPlayoffBirth": 1,
      "EliminatedConference": 0,
      "EliminatedDivision": 0,
      "AheadAtHalf": "44-7 ",
      "BehindAtHalf": "11-16",
      "TiedAtHalf": "3-1  ",
      "AheadAtThird": "51-3 ",
      "BehindAtThird": "7-21 ",
      "TiedAtThird": "0-0  ",
      "Score100PTS": "57-18",
      "OppScore100PTS": "47-23",
      "OppOver500": "28-15",
      "LeadInFGPCT": "50-2 ",
      "LeadInReb": "44-9 ",
      "FewerTurnovers": "15-6 ",
      "PointsPG": 116.9,
      "OppPointsPG": 113.3,
      "DiffPointsPG": 3.6,
      "vsEast": "35-17",
      "vsAtlantic": "12-6",
      "vsCentral": "11-5",
      "vsSoutheast": "12-6",
      "vsWest": "23-7",
      "vsNorthwest": "9-1",
      "vsPacific": "8-2",
      "vsSouthwest": "6-4",
      "Jan": "11-5",
      "Feb": "10-0",
      "Mar": "11-5",
      "Apr": "3-2",
      "May": null,
      "Jun": null,
      "Jul": null,
      "Aug": null,
      "Sep": null,
      "Oct": "6-0",
      "Nov": "9-5",
      "Dec": "8-7",
      "PreAS": "41-17",
      "PostAS": "17-7"
    },
    {
      "LeagueID": "00",
      "SeasonID": "22022",
      "TeamID": 1610612738,
      "TeamCity": "Boston",
      "TeamName": "Celtics",
      "Conference": "East",
      "ConferenceRecord": "34-18",
      "PlayoffRank": 2,
      "ClinchIndicator": " - a",
      "Division": "Atlantic",
      "DivisionRecord": "11-5 ",
      "DivisionRank": 1,
      "WINS": 57,
      "LOSSES": 25,
      "WinPCT": 0.695,
      "LeagueRank": 0,
      "Record": "57-25",
      "HOME": "32-9 ",
      "ROAD": "25-16",
      "L10": "8-2  ",
      "Last10Home": "8-2  ",
      "Last10Road": "5-5  ",
      "OT": "4-7  ",
      "ThreePTSOrLess": "5-8  ",
      "TenPTSOrMore": "31-11",
      "LongHomeStreak": 10,
      "strLongHomeStreak": "W 10",
      "LongRoadStreak": 6,
      "strLongRoadStreak": "W 6",
      "LongWinStreak": 9,
      "LongLossStreak": 3,
      "CurrentHomeStreak": 7,
      "strCurrentHomeStreak": "W 7",
      "CurrentRoadStreak": -1,
      "strCurrentRoadStreak": "L 1",
      "CurrentStreak": 3,
      "strCurrentStreak": "W 3",
      "ConferenceGamesBack": 1.0,
      "DivisionGamesBack": 0.0,
      "ClinchedConferenceTitle": 0,
      "ClinchedDivisionTitle": 1,
      "ClinchedPlayoffBirth": 1,
      "EliminatedConference": 0,
      "EliminatedDivision": 0,
      "AheadAtHalf": "45-9 ",
      "BehindAtHalf": "10-16",
      "TiedAtHalf": "2-0  ",
      "AheadAtThird": "51-7 ",
      "BehindAtThird": "5-18 ",
      "TiedAtThird": "1-0  ",
      "Score100PTS": "56-19",
      "OppScore100PTS": "43-23",
      "OppOver500": "33-14",
      "LeadInFGPCT": "42-4 ",
      "LeadInReb": "36-7 ",
      "FewerTurnovers": "25-9 ",
      "PointsPG": 117.9,
      "OppPointsPG": 111.4,
      "DiffPointsPG": 6.5,
      "vsEast": "34-18",
      "vsAtlantic": "11-5",
      "vsCentral": "11-7",
      "vsSoutheast": "12-6",
      "vsWest": "23-7",
      "vsNorthwest": "7-3",
      "vsPacific": "7-3",
      "vsSouthwest": "9-1",
      "Jan": "10-5",
      "Feb": "8-3",
      "Mar": "10-6",
      "Apr": "3-1",
      "May": null,
      "Jun": null,
      "Jul": null,
      "Aug": null,
      "Sep": null,
      "Oct": "4-2",
      "Nov": "14-2",
      "Dec": "8-6",
      "PreAS": "42-17",
      "PostAS": "15-8"
    },
    {
      "LeagueID": "00",
      "SeasonID": "22022",
      "TeamID": 1610612763,
      "TeamCity": "Memphis",
      "TeamName": "Grizzlies",
      "Conference": "West",
      "ConferenceRecord": "30-22",
      "PlayoffRank": 2,
      "ClinchIndicator": " - sw",
      "Division": "Southwest",
      "DivisionRecord": "13-3 ",
      "DivisionRank": 1,
      "WINS": 51,
      "LOSSES": 31,
      "WinPCT": 0.622,
      "LeagueRank": 0,
      "Record": "51-31",
      "HOME": "35-6 ",
      "ROAD": "16-25",
      "L10": "6-4  ",
      "Last10Home": "9-1  ",
      "Last10Road": "4-6  ",
      "OT": "3-1  ",
      "ThreePTSOrLess": "3-6  ",
      "TenPTSOrMore": "31-17",
      "LongHomeStreak": 12,
      "strLongHomeStreak": "W 12",
      "LongRoadStreak": -8,
      "strLongRoadStreak": "L 8",
      "LongWinStreak": 11,
      "LongLossStreak": 5,
      "CurrentHomeStreak": 2,
      "strCurrentHomeStreak": "W 2",
      "CurrentRoadStreak": -1,
      "strCurrentRoadStreak": "L 1",
      "CurrentStreak": -1,
      "strCurrentStreak": "L 1",
      "ConferenceGamesBack": 2.0,
      "DivisionGamesBack": 0.0,
      "ClinchedConferenceTitle": 0,
      "ClinchedDivisionTitle": 1,
      "ClinchedPlayoffBirth": 1,
      "EliminatedConference": 0,
      "EliminatedDivision": 0,
      "AheadAtHalf": "43-13",
      "BehindAtHalf": "8-18 ",
      "TiedAtHalf": "0-0  ",
      "AheadAtThird": "44-8 ",
      "BehindAtThird": "7-21 ",
      "TiedAtThird": "0-2  ",
      "Score100PTS": "51-27",
      "OppScore100PTS": "43-31",
      "OppOver500": "22-18",
      "LeadInFGPCT": "41-6 ",
      "LeadInReb": "36-16",
      "FewerTurnovers": "31-14",
      "PointsPG": 116.9,
      "OppPointsPG": 113.0,
      "DiffPointsPG": 3.9,
      "vsEast": "21-9",
      "vsAtlantic": "5-5",
      "vsCentral": "8-2",
      "vsSoutheast": "8-2",
      "vsWest": "30-22",
      "vsNorthwest": "9-9",
      "vsPacific": "8-10",
      "vsSouthwest": "13-3",
      "Jan": "10-5",
      "Feb": "5-5",
      "Mar": "12-5",
      "Apr": "2-3",
      "May": null,
      "Jun": null,
      "Jul": null,
      "Aug": null,
      "Sep": null,
      "Oct": "4-3",
      "Nov": "8-6",
      "Dec": "10-4",
      "PreAS": "35-22",
      "PostAS": "16-9"
    },
    {
      "LeagueID": "00",
      "SeasonID": "22022",
      "TeamID": 1610612758,
      "TeamCity": "Sacramento",
      "TeamName": "Kings",
      "Conference": "West",
      "ConferenceRecord": "32-20",
      "PlayoffRank": 3,
      "ClinchIndicator": " - p",
      "Division": "Pacific",
      "DivisionRecord": "9-7  ",
      "DivisionRank": 1,
      "WINS": 48,
      "LOSSES": 34,
      "WinPCT": 0.585,
      "LeagueRank": 0,
      "Record": "48-34",
      "HOME": "23-18",
      "ROAD": "25-16",
      "L10": "5-5  ",
      "Last10Home": "4-6  ",
      "Last10Road": "7-3  ",
      "OT": "4-1  ",
      "ThreePTSOrLess": "9-7  ",
      "TenPTSOrMore": "19-13",
      "LongHomeStreak": 6,
      "strLongHomeStreak": "W 6",
      "LongRoadStreak": 7,
      "strLongRoadStreak": "W 7",
      "LongWinStreak": 7,
      "LongLossStreak": 4,
      "CurrentHomeStreak": -3,
      "strCurrentHomeStreak": "L 3",
      "CurrentRoadStreak": -2,
      "strCurrentRoadStreak": "L 2",
      "CurrentStreak": -3,
      "strCurrentStreak": "L 3",
      "ConferenceGamesBack": 5.0,
      "DivisionGamesBack": 0.0,
      "ClinchedConferenceTitle": 0,
      "ClinchedDivisionTitle": 1,
      "ClinchedPlayoffBirth": 1,
      "EliminatedConference": 0,
      "EliminatedDivision": 0,
      "AheadAtHalf": "30-11",
      "BehindAtHalf": "16-22",
      "TiedAtHalf": "2-1  ",
      "AheadAtThird": "38-3 ",
      "BehindAtThird": "9-27 ",
      "TiedAtThird": "1-4  ",
      "Score100PTS": "48-30",
      "OppScore100PTS": "44-34",
      "OppOver500": "18-23",
      "LeadInFGPCT": "32-5 ",
      "LeadInReb": "28-10",
      "FewerTurnovers": "29-16",
      "PointsPG": 120.7,
      "OppPointsPG": 118.1,
      "DiffPointsPG": 2.6,
      "vsEast": "16-14",
      "vsAtlantic": "4-6",
      "vsCentral": "7-3",
      "vsSoutheast": "5-5",
      "vsWest": "32-20",
      "vsNorthwest": "11-7",
      "vsPacific": "9-7",
      "vsSouthwest": "12-6",
      "Jan": "9-6",
      "Feb": "8-4",
      "Mar": "11-5",
      "Apr": "1-4",
      "May": null,
      "Jun": null,
      "Jul": null,
      "Aug": null,
      "Sep": null,
      "Oct": "2-4",
      "Nov": "9-5",
      "Dec": "8-6",
      "PreAS": "32-25",
      "PostAS": "16-9"
    },
    {
      "LeagueID": "00",
      "SeasonID": "22022",
      "TeamID": 1610612755,
      "TeamCity": "Philadelphia",
      "TeamName": "76ers",
      "Conference": "East",
      "ConferenceRecord": "34-18",
      "PlayoffRank": 3,
      "ClinchIndicator": " - x",
      "Division": "Atlantic",
      "DivisionRecord": "10-6 ",
      "DivisionRank": 2,
      "WINS": 54,
      "LOSSES": 28,
      "WinPCT": 0.659,
      "LeagueRank": 0,
      "Record": "54-28",
      "HOME": "29-12",
      "ROAD": "25-16",
      "L10": "5-5  ",
      "Last10Home": "6-4  ",
      "Last10Road": "6-4  ",
      "OT": "4-2  ",
      "ThreePTSOrLess": "10-5 ",
      "TenPTSOrMore": "26-11",
      "LongHomeStreak": 11,
      "strLongHomeStreak": "W 11",
      "LongRoadStreak": 8,
      "strLongRoadStreak": "W 8",
      "LongWinStreak": 8,
      "LongLossStreak": 3,
      "CurrentHomeStreak": -1,
      "strCurrentHomeStreak": "L 1",
      "CurrentRoadStreak": 2,
      "strCurrentRoadStreak": "W 2",
      "CurrentStreak": 2,
      "strCurrentStreak": "W 2",
      "ConferenceGamesBack": 4.0,
      "DivisionGamesBack": 3.0,
      "ClinchedConferenceTitle": 0,
      "ClinchedDivisionTitle": 0,
      "ClinchedPlayoffBirth": 1,
      "EliminatedConference": 0,
      "EliminatedDivision": 0,
      "AheadAtHalf": "34-4 ",
      "BehindAtHalf": "19-23",
      "TiedAtHalf": "1-1  ",
      "AheadAtThird": "40-3 ",
      "BehindAtThird": "9-25 ",
      "TiedAtThird": "5-0  ",
      "Score100PTS": "54-22",
      "OppScore100PTS": "40-27",
      "OppOver500": "29-18",
      "LeadInFGPCT": "36-11",
      "LeadInReb": "31-4 ",
      "FewerTurnovers": "32-13",
      "PointsPG": 115.2,
      "OppPointsPG": 110.9,
      "DiffPointsPG": 4.3,
      "vsEast": "34-18",
      "vsAtlantic": "10-6",
      "vsCentral": "13-5",
      "vsSoutheast": "11-7",
      "vsWest": "20-10",
      "vsNorthwest": "7-3",
      "vsPacific": "8-2",
      "vsSouthwest": "5-5",
      "Jan": "11-3",
      "Feb": "7-4",
      "Mar": "12-5",
      "Apr": "3-2",
      "May": null,
      "Jun": null,
      "Jul": null,
      "Aug": null,
      "Sep": null,
      "Oct": "4-4",
      "Nov": "8-6",
      "Dec": "9-4",
      "PreAS": "38-19",
      "PostAS": "16-9"
    },
    {
      "LeagueID": "00",
      "SeasonID": "22022",
      "TeamID": 1610612739,
      "TeamCity": "Cleveland",
      "TeamName": "Cavaliers",
      "Conference": "East",
      "ConferenceRecord": "34-18",
      "PlayoffRank": 4,
      "ClinchIndicator": " - x",
      "Division": "Central",
      "DivisionRecord": "13-3 ",
      "DivisionRank": 2,
      "WINS": 51,
      "LOSSES": 31,
      "WinPCT": 0.622,
      "LeagueRank": 0,
      "Record": "51-31",
      "HOME": "31-10",
      "ROAD": "20-21",
      "L10": "7-3  ",
      "Last10Home": "6-4  ",
      "Last10Road": "7-3  ",
      "OT": "7-0  ",
      "ThreePTSOrLess": "5-8  ",
      "TenPTSOrMore": "33-11",
      "LongHomeStreak": 7,
      "strLongHomeStreak": "W 7",
      "LongRoadStreak": -5,
      "strLongRoadStreak": "L 5",
      "LongWinStreak": 8,
      "LongLossStreak": 5,
      "CurrentHomeStreak": -1,
      "strCurrentHomeStreak": "L 1",
      "CurrentRoadStreak": 2,
      "strCurrentRoadStreak": "W 2",
      "CurrentStreak": -1,
      "strCurrentStreak": "L 1",
      "ConferenceGamesBack": 7.0,
      "DivisionGamesBack": 7.0,
      "ClinchedConferenceTitle": 0,
      "ClinchedDivisionTitle": 0,
      "ClinchedPlayoffBirth": 1,
      "EliminatedConference": 0,
      "EliminatedDivision": 0,
      "AheadAtHalf": "35-10",
      "BehindAtHalf": "16-18",
      "TiedAtHalf": "0-3  ",
      "AheadAtThird": "37-8 ",
      "BehindAtThird": "14-21",
      "TiedAtThird": "0-2  ",
      "Score100PTS": "49-25",
      "OppScore100PTS": "28-30",
      "OppOver500": "24-18",
      "LeadInFGPCT": "33-11",
      "LeadInReb": "32-7 ",
      "FewerTurnovers": "31-22",
      "PointsPG": 112.3,
      "OppPointsPG": 106.9,
      "DiffPointsPG": 5.4,
      "vsEast": "34-18",
      "vsAtlantic": "8-10",
      "vsCentral": "13-3",
      "vsSoutheast": "13-5",
      "vsWest": "17-13",
      "vsNorthwest": "4-6",
      "vsPacific": "5-5",
      "vsSouthwest": "8-2",
      "Jan": "8-8",
      "Feb": "8-3",
      "Mar": "9-5",
      "Apr": "3-1",
      "May": null,
      "Jun": null,
      "Jul": null,
      "Aug": null,
      "Sep": null,
      "Oct": "5-1",
      "Nov": "9-7",
      "Dec": "9-6",
      "PreAS": "38-23",
      "PostAS": "13-8"
    },
    {
      "LeagueID": "00",
      "SeasonID": "22022",
      "TeamID": 1610612756,
      "TeamCity": "Phoenix",
      "TeamName": "Suns",
      "Conference": "West",
      "ConferenceRecord": "30-22",
      "PlayoffRank": 4,
      "ClinchIndicator": " - x",
      "Division": "Pacific",
      "DivisionRecord": "9-7  ",
      "DivisionRank": 2,
      "WINS": 45,
      "LOSSES": 37,
      "WinPCT": 0.549,
      "LeagueRank": 0,
      "Record": "45-37",
      "HOME": "28-13",
      "ROAD": "17-24",
      "L10": "7-3  ",
      "Last10Home": "7-3  ",
      "Last10Road": "5-5  ",
      "OT": "1-3  ",
      "ThreePTSOrLess": "4-9  ",
      "TenPTSOrMore": "28-17",
      "LongHomeStreak": 7,
      "strLongHomeStreak": "W 7",
      "LongRoadStreak": 4,
      "strLongRoadStreak": "W 4",
      "LongWinStreak": 7,
      "LongLossStreak": 6,
      "CurrentHomeStreak": -1,
      "strCurrentHomeStreak": "L 1",
      "CurrentRoadStreak": -1,
      "strCurrentRoadStreak": "L 1",
      "CurrentStreak": -2,
      "strCurrentStreak": "L 2",
      "ConferenceGamesBack": 8.0,
      "DivisionGamesBack": 3.0,
      "ClinchedConferenceTitle": 0,
      "ClinchedDivisionTitle": 0,
      "ClinchedPlayoffBirth": 1,
      "EliminatedConference": 0,
      "EliminatedDivision": 0,
      "AheadAtHalf": "36-9 ",
      "BehindAtHalf": "9-28 ",
      "TiedAtHalf": "0-0  ",
      "AheadAtThird": "41-7 ",
      "BehindAtThird": "4-30 ",
      "TiedAtThird": "0-0  ",
      "Score100PTS": "45-27",
      "OppScore100PTS": "35-35",
      "OppOver500": "23-24",
      "LeadInFGPCT": "36-8 ",
      "LeadInReb": "29-14",
      "FewerTurnovers": "29-16",
      "PointsPG": 113.6,
      "OppPointsPG": 111.6,
      "DiffPointsPG": 2.1,
      "vsEast": "15-15",
      "vsAtlantic": "6-4",
      "vsCentral": "6-4",
      "vsSoutheast": "3-7",
      "vsWest": "30-22",
      "vsNorthwest": "11-7",
      "vsPacific": "9-7",
      "vsSouthwest": "10-8",
      "Jan": "7-8",
      "Feb": "6-4",
      "Mar": "9-6",
      "Apr": "3-2",
      "May": null,
      "Jun": null,
      "Jul": null,
      "Aug": null,
      "Sep": null,
      "Oct": "5-1",
      "Nov": "10-5",
      "Dec": "5-11",
      "PreAS": "32-28",
      "PostAS": "13-9"
    },
    {
      "LeagueID": "00",
      "SeasonID": "22022",
      "TeamID": 1610612746,
      "TeamCity": "LA",
      "TeamName": "Clippers",
      "Conference": "West",
      "ConferenceRecord": "27-25",
      "PlayoffRank": 5,
      "ClinchIndicator": " - x",
      "Division": "Pacific",
      "DivisionRecord": "9-7  ",
      "DivisionRank": 3,
      "WINS": 44,
      "LOSSES": 38,
      "WinPCT": 0.537,
      "LeagueRank": 0,
      "Record": "44-38",
      "HOME": "23-18",
      "ROAD": "21-20",
      "L10": "6-4  ",
      "Last10Home": "7-3  ",
      "Last10Road": "5-5  ",
      "OT": "2-3  ",
      "ThreePTSOrLess": "4-6  ",
      "TenPTSOrMore": "20-21",
      "LongHomeStreak": 4,
      "strLongHomeStreak": "W 4",
      "LongRoadStreak": -5,
      "strLongRoadStreak": "L 5",
      "LongWinStreak": 5,
      "LongLossStreak": 6,
      "CurrentHomeStreak": 3,
      "strCurrentHomeStreak": "W 3",
      "CurrentRoadStreak": 1,
      "strCurrentRoadStreak": "W 1",
      "CurrentStreak": 3,
      "strCurrentStreak": "W 3",
      "ConferenceGamesBack": 9.0,
      "DivisionGamesBack": 4.0,
      "ClinchedConferenceTitle": 0,
      "ClinchedDivisionTitle": 0,
      "ClinchedPlayoffBirth": 1,
      "EliminatedConference": 0,
      "EliminatedDivision": 0,
      "AheadAtHalf": "24-9 ",
      "BehindAtHalf": "16-28",
      "TiedAtHalf": "4-1  ",
      "AheadAtThird": "33-10",
      "BehindAtThird": "9-26 ",
      "TiedAtThird": "2-2  ",
      "Score100PTS": "41-28",
      "OppScore100PTS": "35-38",
      "OppOver500": "20-25",
      "LeadInFGPCT": "32-10",
      "LeadInReb": "28-8 ",
      "FewerTurnovers": "20-10",
      "PointsPG": 113.6,
      "OppPointsPG": 113.1,
      "DiffPointsPG": 0.5,
      "vsEast": "17-13",
      "vsAtlantic": "6-4",
      "vsCentral": "6-4",
      "vsSoutheast": "5-5",
      "vsWest": "27-25",
      "vsNorthwest": "6-12",
      "vsPacific": "9-7",
      "vsSouthwest": "12-6",
      "Jan": "8-8",
      "Feb": "4-6",
      "Mar": "8-6",
      "Apr": "3-1",
      "May": null,
      "Jun": null,
      "Jul": null,
      "Aug": null,
      "Sep": null,
      "Oct": "3-4",
      "Nov": "10-6",
      "Dec": "8-7",
      "PreAS": "33-28",
      "PostAS": "11-10"
    },
    {
      "LeagueID": "00",
      "SeasonID": "22022",
      "TeamID": 1610612752,
      "TeamCity": "New York",
      "TeamName": "Knicks",
      "Conference": "East",
      "ConferenceRecord": "32-20",
      "PlayoffRank": 5,
      "ClinchIndicator": " - x",
      "Division": "Atlantic",
      "DivisionRecord": "8-8  ",
      "DivisionRank": 3,
      "WINS": 47,
      "LOSSES": 35,
      "WinPCT": 0.573,
      "LeagueRank": 0,
      "Record": "47-35",
      "HOME": "23-18",
      "ROAD": "24-17",
      "L10": "5-5  ",
      "Last10Home": "7-3  ",
      "Last10Road": "5-5  ",
      "OT": "4-6  ",
      "ThreePTSOrLess": "10-4 ",
      "TenPTSOrMore": "23-13",
      "LongHomeStreak": 6,
      "strLongHomeStreak": "W 6",
      "LongRoadStreak": 6,
      "strLongRoadStreak": "W 6",
      "LongWinStreak": 9,
      "LongLossStreak": 5,
      "CurrentHomeStreak": -1,
      "strCurrentHomeStreak": "L 1",
      "CurrentRoadStreak": -1,
      "strCurrentRoadStreak": "L 1",
      "CurrentStreak": -2,
      "strCurrentStreak": "L 2",
      "ConferenceGamesBack": 11.0,
      "DivisionGamesBack": 10.0,
      "ClinchedConferenceTitle": 0,
      "ClinchedDivisionTitle": 0,
      "ClinchedPlayoffBirth": 1,
      "EliminatedConference": 0,
      "EliminatedDivision": 0,
      "AheadAtHalf": "37-12",
      "BehindAtHalf": "10-22",
      "TiedAtHalf": "0-1  ",
      "AheadAtThird": "38-9 ",
      "BehindAtThird": "7-23 ",
      "TiedAtThird": "2-3  ",
      "Score100PTS": "46-31",
      "OppScore100PTS": "36-35",
      "OppOver500": "25-20",
      "LeadInFGPCT": "36-12",
      "LeadInReb": "39-16",
      "FewerTurnovers": "18-13",
      "PointsPG": 116.0,
      "OppPointsPG": 113.1,
      "DiffPointsPG": 2.9,
      "vsEast": "32-20",
      "vsAtlantic": "8-8",
      "vsCentral": "12-6",
      "vsSoutheast": "12-6",
      "vsWest": "15-15",
      "vsNorthwest": "7-3",
      "vsPacific": "4-6",
      "vsSouthwest": "4-6",
      "Jan": "8-7",
      "Feb": "9-2",
      "Mar": "9-6",
      "Apr": "2-2",
      "May": null,
      "Jun": null,
      "Jul": null,
      "Aug": null,
      "Sep": null,
      "Oct": "3-3",
      "Nov": "7-9",
      "Dec": "9-6",
      "PreAS": "33-27",
      "PostAS": "14-8"
    },
    {
      "LeagueID": "00",
      "SeasonID": "22022",
      "TeamID": 1610612744,
      "TeamCity": "Golden State",
      "TeamName": "Warriors",
      "Conference": "West",
      "ConferenceRecord": "30-22",
      "PlayoffRank": 6,
      "ClinchIndicator": " - x",
      "Division": "Pacific",
      "DivisionRecord": "7-9  ",
      "DivisionRank": 4,
      "WINS": 44,
      "LOSSES": 38,
      "WinPCT": 0.537,
      "LeagueRank": 0,
      "Record": "44-38",
      "HOME": "33-8 ",
      "ROAD": "11-30",
      "L10": "8-2  ",
      "Last10Home": "9-1  ",
      "Last10Road": "4-6  ",
      "OT": "2-3  ",
      "ThreePTSOrLess": "4-8  ",
      "TenPTSOrMore": "24-16",
      "LongHomeStreak": 10,
      "strLongHomeStreak": "W 10",
      "LongRoadStreak": -11,
      "strLongRoadStreak": "L 11",
      "LongWinStreak": 5,
      "LongLossStreak": 5,
      "CurrentHomeStreak": 3,
      "strCurrentHomeStreak": "W 3",
      "CurrentRoadStreak": 2,
      "strCurrentRoadStreak": "W 2",
      "CurrentStreak": 3,
      "strCurrentStreak": "W 3",
      "ConferenceGamesBack": 9.0,
      "DivisionGamesBack": 4.0,
      "ClinchedConferenceTitle": 0,
      "ClinchedDivisionTitle": 0,
      "ClinchedPlayoffBirth": 1,
      "EliminatedConference": 0,
      "EliminatedDivision": 0,
      "AheadAtHalf": "34-12",
      "BehindAtHalf": "10-26",
      "TiedAtHalf": "0-0  ",
      "AheadAtThird": "32-6 ",
      "BehindAtThird": "10-31",
      "TiedAtThird": "2-1  ",
      "Score100PTS": "44-35",
      "OppScore100PTS": "40-37",
      "OppOver500": "21-21",
      "LeadInFGPCT": "38-8 ",
      "LeadInReb": "31-12",
      "FewerTurnovers": "13-12",
      "PointsPG": 118.9,
      "OppPointsPG": 117.1,
      "DiffPointsPG": 1.8,
      "vsEast": "14-16",
      "vsAtlantic": "5-5",
      "vsCentral": "4-6",
      "vsSoutheast": "5-5",
      "vsWest": "30-22",
      "vsNorthwest": "10-8",
      "vsPacific": "7-9",
      "vsSouthwest": "13-5",
      "Jan": "7-6",
      "Feb": "6-6",
      "Mar": "9-7",
      "Apr": "3-1",
      "May": null,
      "Jun": null,
      "Jul": null,
      "Aug": null,
      "Sep": null,
      "Oct": "3-4",
      "Nov": "8-7",
      "Dec": "8-7",
      "PreAS": "29-29",
      "PostAS": "15-9"
    },
    {
      "LeagueID": "00",
      "SeasonID": "22022",
      "TeamID": 1610612751,
      "TeamCity": "Brooklyn",
      "TeamName": "Nets",
      "Conference": "East",
      "ConferenceRecord": "30-22",
      "PlayoffRank": 6,
      "ClinchIndicator": " - x",
      "Division": "Atlantic",
      "DivisionRecord": "7-9  ",
      "DivisionRank": 4,
      "WINS": 45,
      "LOSSES": 37,
      "WinPCT": 0.549,
      "LeagueRank": 0,
      "Record": "45-37",
      "HOME": "23-18",
      "ROAD": "22-19",
      "L10": "6-4  ",
      "Last10Home": "4-6  ",
      "Last10Road": "6-4  ",
      "OT": "1-1  ",
      "ThreePTSOrLess": "10-4 ",
      "TenPTSOrMore": "22-17",
      "LongHomeStreak": 6,
      "strLongHomeStreak": "W 6",
      "LongRoadStreak": 7,
      "strLongRoadStreak": "W 7",
      "LongWinStreak": 12,
      "LongLossStreak": 5,
      "CurrentHomeStreak": -1,
      "strCurrentHomeStreak": "L 1",
      "CurrentRoadStreak": 1,
      "strCurrentRoadStreak": "W 1",
      "CurrentStreak": -1,
      "strCurrentStreak": "L 1",
      "ConferenceGamesBack": 13.0,
      "DivisionGamesBack": 12.0,
      "ClinchedConferenceTitle": 0,
      "ClinchedDivisionTitle": 0,
      "ClinchedPlayoffBirth": 1,
      "EliminatedConference": 0,
      "EliminatedDivision": 0,
      "AheadAtHalf": "28-12",
      "BehindAtHalf": "17-24",
      "TiedAtHalf": "0-1  ",
      "AheadAtThird": "36-7 ",
      "BehindAtThird": "8-30 ",
      "TiedAtThird": "1-0  ",
      "Score100PTS": "44-27",
      "OppScore100PTS": "36-36",
      "OppOver500": "26-24",
      "LeadInFGPCT": "39-12",
      "LeadInReb": "16-6 ",
      "FewerTurnovers": "25-16",
      "PointsPG": 113.4,
      "OppPointsPG": 112.5,
      "DiffPointsPG": 0.9,
      "vsEast": "30-22",
      "vsAtlantic": "7-9",
      "vsCentral": "7-11",
      "vsSoutheast": "16-2",
      "vsWest": "15-15",
      "vsNorthwest": "6-4",
      "vsPacific": "4-6",
      "vsSouthwest": "5-5",
      "Jan": "7-7",
      "Feb": "3-8",
      "Mar": "8-8",
      "Apr": "3-2",
      "May": null,
      "Jun": null,
      "Jul": null,
      "Aug": null,
      "Sep": null,
      "Oct": "2-5",
      "Nov": "10-6",
      "Dec": "12-1",
      "PreAS": "34-24",
      "PostAS": "11-13"
    },
    {
      "LeagueID": "00",
      "SeasonID": "22022",
      "TeamID": 1610612747,
      "TeamCity": "Los Angeles",
      "TeamName": "Lakers",
      "Conference": "West",
      "ConferenceRecord": "27-25",
      "PlayoffRank": 7,
      "ClinchIndicator": "",
      "Division": "Pacific",
      "DivisionRecord": "6-10 ",
      "DivisionRank": 5,
      "WINS": 43,
      "LOSSES": 39,
      "WinPCT": 0.524,
      "LeagueRank": 0,
      "Record": "43-39",
      "HOME": "23-18",
      "ROAD": "20-21",
      "L10": "8-2  ",
      "Last10Home": "7-3  ",
      "Last10Road": "7-3  ",
      "OT": "3-4  ",
      "ThreePTSOrLess": "8-5  ",
      "TenPTSOrMore": "19-19",
      "LongHomeStreak": 3,
      "strLongHomeStreak": "W 3",
      "LongRoadStreak": -6,
      "strLongRoadStreak": "L 6",
      "LongWinStreak": 5,
      "LongLossStreak": 5,
      "CurrentHomeStreak": 2,
      "strCurrentHomeStreak": "W 2",
      "CurrentRoadStreak": -1,
      "strCurrentRoadStreak": "L 1",
      "CurrentStreak": 2,
      "strCurrentStreak": "W 2",
      "ConferenceGamesBack": 10.0,
      "DivisionGamesBack": 5.0,
      "ClinchedConferenceTitle": 0,
      "ClinchedDivisionTitle": 0,
      "ClinchedPlayoffBirth": 0,
      "EliminatedConference": 0,
      "EliminatedDivision": 0,
      "AheadAtHalf": "29-10",
      "BehindAtHalf": "13-25",
      "TiedAtHalf": "1-4  ",
      "AheadAtThird": "35-5 ",
      "BehindAtThird": "7-33 ",
      "TiedAtThird": "1-1  ",
      "Score100PTS": "43-36",
      "OppScore100PTS": "41-39",
      "OppOver500": "18-32",
      "LeadInFGPCT": "37-11",
      "LeadInReb": "32-14",
      "FewerTurnovers": "15-13",
      "PointsPG": 117.2,
      "OppPointsPG": 116.6,
      "DiffPointsPG": 0.6,
      "vsEast": "16-14",
      "vsAtlantic": "3-7",
      "vsCentral": "5-5",
      "vsSoutheast": "8-2",
      "vsWest": "27-25",
      "vsNorthwest": "9-9",
      "vsPacific": "6-10",
      "vsSouthwest": "12-6",
      "Jan": "9-7",
      "Feb": "5-5",
      "Mar": "10-5",
      "Apr": "4-1",
      "May": null,
      "Jun": null,
      "Jul": null,
      "Aug": null,
      "Sep": null,
      "Oct": "1-5",
      "Nov": "7-7",
      "Dec": "7-9",
      "PreAS": "27-32",
      "PostAS": "16-7"
    },
    {
      "LeagueID": "00",
      "SeasonID": "22022",
      "TeamID": 1610612737,
      "TeamCity": "Atlanta",
      "TeamName": "Hawks",
      "Conference": "East",
      "ConferenceRecord": "26-26",
      "PlayoffRank": 7,
      "ClinchIndicator": "",
      "Division": "Southeast",
      "DivisionRecord": "8-8  ",
      "DivisionRank": 2,
      "WINS": 41,
      "LOSSES": 41,
      "WinPCT": 0.5,
      "LeagueRank": 0,
      "Record": "41-41",
      "HOME": "24-17",
      "ROAD": "17-24",
      "L10": "5-5  ",
      "Last10Home": "6-4  ",
      "Last10Road": "3-7  ",
      "OT": "4-2  ",
      "ThreePTSOrLess": "10-7 ",
      "TenPTSOrMore": "19-15",
      "LongHomeStreak": 3,
      "strLongHomeStreak": "W 3",
      "LongRoadStreak": -5,
      "strLongRoadStreak": "L 5",
      "LongWinStreak": 5,
      "LongLossStreak": 4,
      "CurrentHomeStreak": -1,
      "strCurrentHomeStreak": "L 1",
      "CurrentRoadStreak": -1,
      "strCurrentRoadStreak": "L 1",
      "CurrentStreak": -2,
      "strCurrentStreak": "L 2",
      "ConferenceGamesBack": 17.0,
      "DivisionGamesBack": 3.0,
      "ClinchedConferenceTitle": 0,
      "ClinchedDivisionTitle": 0,
      "ClinchedPlayoffBirth": 0,
      "EliminatedConference": 0,
      "EliminatedDivision": 0,
      "AheadAtHalf": "31-12",
      "BehindAtHalf": "9-29 ",
      "TiedAtHalf": "1-0  ",
      "AheadAtThird": "35-9 ",
      "BehindAtThird": "5-29 ",
      "TiedAtThird": "1-3  ",
      "Score100PTS": "41-39",
      "OppScore100PTS": "37-41",
      "OppOver500": "21-25",
      "LeadInFGPCT": "32-7 ",
      "LeadInReb": "25-15",
      "FewerTurnovers": "26-23",
      "PointsPG": 118.4,
      "OppPointsPG": 118.1,
      "DiffPointsPG": 0.3,
      "vsEast": "26-26",
      "vsAtlantic": "6-12",
      "vsCentral": "12-6",
      "vsSoutheast": "8-8",
      "vsWest": "15-15",
      "vsNorthwest": "4-6",
      "vsPacific": "6-4",
      "vsSouthwest": "5-5",
      "Jan": "8-7",
      "Feb": "6-5",
      "Mar": "7-8",
      "Apr": "3-2",
      "May": null,
      "Jun": null,
      "Jul": null,
      "Aug": null,
      "Sep": null,
      "Oct": "4-3",
      "Nov": "8-7",
      "Dec": "5-9",
      "PreAS": "29-30",
      "PostAS": "12-11"
    },
    {
      "LeagueID": "00",
      "SeasonID": "22022",
      "TeamID": 1610612748,
      "TeamCity": "Miami",
      "TeamName": "Heat",
      "Conference": "East",
      "ConferenceRecord": "24-28",
      "PlayoffRank": 8,
      "ClinchIndicator": " - se",
      "Division": "Southeast",
      "DivisionRecord": "10-6 ",
      "DivisionRank": 1,
      "WINS": 44,
      "LOSSES": 38,
      "WinPCT": 0.537,
      "LeagueRank": 0,
      "Record": "44-38",
      "HOME": "27-14",
      "ROAD": "17-24",
      "L10": "6-4  ",
      "Last10Home": "8-2  ",
      "Last10Road": "4-6  ",
      "OT": "3-2  ",
      "ThreePTSOrLess": "14-8 ",
      "TenPTSOrMore": "12-13",
      "LongHomeStreak": 8,
      "strLongHomeStreak": "W 8",
      "LongRoadStreak": -7,
      "strLongRoadStreak": "L 7",
      "LongWinStreak": 4,
      "LongLossStreak": 4,
      "CurrentHomeStreak": 2,
      "strCurrentHomeStreak": "W 2",
      "CurrentRoadStreak": -1,
      "strCurrentRoadStreak": "L 1",
      "CurrentStreak": 1,
      "strCurrentStreak": "W 1",
      "ConferenceGamesBack": 14.0,
      "DivisionGamesBack": 0.0,
      "ClinchedConferenceTitle": 0,
      "ClinchedDivisionTitle": 1,
      "ClinchedPlayoffBirth": 0,
      "EliminatedConference": 0,
      "EliminatedDivision": 0,
      "AheadAtHalf": "30-10",
      "BehindAtHalf": "13-26",
      "TiedAtHalf": "1-2  ",
      "AheadAtThird": "26-5 ",
      "BehindAtThird": "15-32",
      "TiedAtThird": "3-1  ",
      "Score100PTS": "41-27",
      "OppScore100PTS": "32-37",
      "OppOver500": "25-24",
      "LeadInFGPCT": "25-4 ",
      "LeadInReb": "26-10",
      "FewerTurnovers": "28-23",
      "PointsPG": 109.5,
      "OppPointsPG": 109.8,
      "DiffPointsPG": -0.3,
      "vsEast": "24-28",
      "vsAtlantic": "6-12",
      "vsCentral": "8-10",
      "vsSoutheast": "10-6",
      "vsWest": "20-10",
      "vsNorthwest": "6-4",
      "vsPacific": "7-3",
      "vsSouthwest": "7-3",
      "Jan": "10-5",
      "Feb": "4-6",
      "Mar": "7-8",
      "Apr": "4-1",
      "May": null,
      "Jun": null,
      "Jul": null,
      "Aug": null,
      "Sep": null,
      "Oct": "2-5",
      "Nov": "8-7",
      "Dec": "9-6",
      "PreAS": "32-27",
      "PostAS": "12-11"
    },
    {
      "LeagueID": "00",
      "SeasonID": "22022",
      "TeamID": 1610612750,
      "TeamCity": "Minnesota",
      "TeamName": "Timberwolves",
      "Conference": "West",
      "ConferenceRecord": "29-23",
      "PlayoffRank": 8,
      "ClinchIndicator": "",
      "Division": "Northwest",
      "DivisionRecord": "8-8  ",
      "DivisionRank": 2,
      "WINS": 42,
      "LOSSES": 40,
      "WinPCT": 0.512,
      "LeagueRank": 0,
      "Record": "42-40",
      "HOME": "22-19",
      "ROAD": "20-21",
      "L10": "7-3  ",
      "Last10Home": "3-7  ",
      "Last10Road": "7-3  ",
      "OT": "1-4  ",
      "ThreePTSOrLess": "6-7  ",
      "TenPTSOrMore": "15-16",
      "LongHomeStreak": 5,
      "strLongHomeStreak": "W 5",
      "LongRoadStreak": 4,
      "strLongRoadStreak": "W 4",
      "LongWinStreak": 5,
      "LongLossStreak": 6,
      "CurrentHomeStreak": 1,
      "strCurrentHomeStreak": "W 1",
      "CurrentRoadStreak": 2,
      "strCurrentRoadStreak": "W 2",
      "CurrentStreak": 3,
      "strCurrentStreak": "W 3",
      "ConferenceGamesBack": 11.0,
      "DivisionGamesBack": 11.0,
      "ClinchedConferenceTitle": 0,
      "ClinchedDivisionTitle": 0,
      "ClinchedPlayoffBirth": 0,
      "EliminatedConference": 0,
      "EliminatedDivision": 0,
      "AheadAtHalf": "28-18",
      "BehindAtHalf": "13-21",
      "TiedAtHalf": "1-1  ",
      "AheadAtThird": "32-9 ",
      "BehindAtThird": "8-30 ",
      "TiedAtThird": "2-1  ",
      "Score100PTS": "41-36",
      "OppScore100PTS": "39-39",
      "OppOver500": "28-25",
      "LeadInFGPCT": "36-15",
      "LeadInReb": "19-12",
      "FewerTurnovers": "24-14",
      "PointsPG": 115.8,
      "OppPointsPG": 115.8,
      "DiffPointsPG": 0.0,
      "vsEast": "13-17",
      "vsAtlantic": "4-6",
      "vsCentral": "5-5",
      "vsSoutheast": "4-6",
      "vsWest": "29-23",
      "vsNorthwest": "8-8",
      "vsPacific": "10-8",
      "vsSouthwest": "11-7",
      "Jan": "11-5",
      "Feb": "5-6",
      "Mar": "7-7",
      "Apr": "3-1",
      "May": null,
      "Jun": null,
      "Jul": null,
      "Aug": null,
      "Sep": null,
      "Oct": "4-3",
      "Nov": "7-8",
      "Dec": "5-10",
      "PreAS": "31-30",
      "PostAS": "11-10"
    },
    {
      "LeagueID": "00",
      "SeasonID": "22022",
      "TeamID": 1610612740,
      "TeamCity": "New Orleans",
      "TeamName": "Pelicans",
      "Conference": "West",
      "ConferenceRecord": "29-23",
      "PlayoffRank": 9,
      "ClinchIndicator": "",
      "Division": "Southwest",
      "DivisionRecord": "11-5 ",
      "DivisionRank": 2,
      "WINS": 42,
      "LOSSES": 40,
      "WinPCT": 0.512,
      "LeagueRank": 0,
      "Record": "42-40",
      "HOME": "27-14",
      "ROAD": "15-26",
      "L10": "7-3  ",
      "Last10Home": "7-3  ",
      "Last10Road": "5-5  ",
      "OT": "3-4  ",
      "ThreePTSOrLess": "4-6  ",
      "TenPTSOrMore": "25-20",
      "LongHomeStreak": 7,
      "strLongHomeStreak": "W 7",
      "LongRoadStreak": -6,
      "strLongRoadStreak": "L 6",
      "LongWinStreak": 7,
      "LongLossStreak": 10,
      "CurrentHomeStreak": 2,
      "strCurrentHomeStreak": "W 2",
      "CurrentRoadStreak": -1,
      "strCurrentRoadStreak": "L 1",
      "CurrentStreak": -1,
      "strCurrentStreak": "L 1",
      "ConferenceGamesBack": 11.0,
      "DivisionGamesBack": 9.0,
      "ClinchedConferenceTitle": 0,
      "ClinchedDivisionTitle": 0,
      "ClinchedPlayoffBirth": 0,
      "EliminatedConference": 0,
      "EliminatedDivision": 0,
      "AheadAtHalf": "31-13",
      "BehindAtHalf": "9-26 ",
      "TiedAtHalf": "2-1  ",
      "AheadAtThird": "34-8 ",
      "BehindAtThird": "7-32 ",
      "TiedAtThird": "1-0  ",
      "Score100PTS": "42-33",
      "OppScore100PTS": "33-39",
      "OppOver500": "19-29",
      "LeadInFGPCT": "35-10",
      "LeadInReb": "34-14",
      "FewerTurnovers": "19-15",
      "PointsPG": 114.4,
      "OppPointsPG": 112.5,
      "DiffPointsPG": 1.9,
      "vsEast": "13-17",
      "vsAtlantic": "4-6",
      "vsCentral": "5-5",
      "vsSoutheast": "4-6",
      "vsWest": "29-23",
      "vsNorthwest": "9-9",
      "vsPacific": "9-9",
      "vsSouthwest": "11-5",
      "Jan": "3-13",
      "Feb": "4-6",
      "Mar": "9-6",
      "Apr": "3-2",
      "May": null,
      "Jun": null,
      "Jul": null,
      "Aug": null,
      "Sep": null,
      "Oct": "4-2",
      "Nov": "9-6",
      "Dec": "10-5",
      "PreAS": "30-29",
      "PostAS": "12-11"
    },
    {
      "LeagueID": "00",
      "SeasonID": "22022",
      "TeamID": 1610612761,
      "TeamCity": "Toronto",
      "TeamName": "Raptors",
      "Conference": "East",
      "ConferenceRecord": "26-26",
      "PlayoffRank": 9,
      "ClinchIndicator": "",
      "Division": "Atlantic",
      "DivisionRecord": "4-12 ",
      "DivisionRank": 5,
      "WINS": 41,
      "LOSSES": 41,
      "WinPCT": 0.5,
      "LeagueRank": 0,
      "Record": "41-41",
      "HOME": "27-14",
      "ROAD": "14-27",
      "L10": "6-4  ",
      "Last10Home": "9-1  ",
      "Last10Road": "3-7  ",
      "OT": "2-3  ",
      "ThreePTSOrLess": "4-10 ",
      "TenPTSOrMore": "23-16",
      "LongHomeStreak": 7,
      "strLongHomeStreak": "W 7",
      "LongRoadStreak": -6,
      "strLongRoadStreak": "L 6",
      "LongWinStreak": 4,
      "LongLossStreak": 6,
      "CurrentHomeStreak": 4,
      "strCurrentHomeStreak": "W 4",
      "CurrentRoadStreak": -2,
      "strCurrentRoadStreak": "L 2",
      "CurrentStreak": 1,
      "strCurrentStreak": "W 1",
      "ConferenceGamesBack": 17.0,
      "DivisionGamesBack": 16.0,
      "ClinchedConferenceTitle": 0,
      "ClinchedDivisionTitle": 0,
      "ClinchedPlayoffBirth": 0,
      "EliminatedConference": 0,
      "EliminatedDivision": 0,
      "AheadAtHalf": "33-11",
      "BehindAtHalf": "6-29 ",
      "TiedAtHalf": "2-1  ",
      "AheadAtThird": "35-11",
      "BehindAtThird": "5-29 ",
      "TiedAtThird": "1-1  ",
      "Score100PTS": "39-35",
      "OppScore100PTS": "33-40",
      "OppOver500": "19-25",
      "LeadInFGPCT": "21-6 ",
      "LeadInReb": "30-16",
      "FewerTurnovers": "33-30",
      "PointsPG": 112.9,
      "OppPointsPG": 111.4,
      "DiffPointsPG": 1.5,
      "vsEast": "26-26",
      "vsAtlantic": "4-12",
      "vsCentral": "10-8",
      "vsSoutheast": "12-6",
      "vsWest": "15-15",
      "vsNorthwest": "5-5",
      "vsPacific": "3-7",
      "vsSouthwest": "7-3",
      "Jan": "7-9",
      "Feb": "8-3",
      "Mar": "7-7",
      "Apr": "3-2",
      "May": null,
      "Jun": null,
      "Jul": null,
      "Aug": null,
      "Sep": null,
      "Oct": "4-3",
      "Nov": "7-7",
      "Dec": "5-10",
      "PreAS": "28-31",
      "PostAS": "13-10"
    },
    {
      "LeagueID": "00",
      "SeasonID": "22022",
      "TeamID": 1610612760,
      "TeamCity": "Oklahoma City",
      "TeamName": "Thunder",
      "Conference": "West",
      "ConferenceRecord": "25-27",
      "PlayoffRank": 10,
      "ClinchIndicator": "",
      "Division": "Northwest",
      "DivisionRecord": "9-7  ",
      "DivisionRank": 3,
      "WINS": 40,
      "LOSSES": 42,
      "WinPCT": 0.488,
      "LeagueRank": 0,
      "Record": "40-42",
      "HOME": "24-17",
      "ROAD": "16-25",
      "L10": "4-6  ",
      "Last10Home": "7-3  ",
      "Last10Road": "5-5  ",
      "OT": "2-4  ",
      "ThreePTSOrLess": "7-7  ",
      "TenPTSOrMore": "21-15",
      "LongHomeStreak": 5,
      "strLongHomeStreak": "W 5",
      "LongRoadStreak": -6,
      "strLongRoadStreak": "L 6",
      "LongWinStreak": 4,
      "LongLossStreak": 5,
      "CurrentHomeStreak": 1,
      "strCurrentHomeStreak": "W 1",
      "CurrentRoadStreak": 1,
      "strCurrentRoadStreak": "W 1",
      "CurrentStreak": 2,
      "strCurrentStreak": "W 2",
      "ConferenceGamesBack": 13.0,
      "DivisionGamesBack": 13.0,
      "ClinchedConferenceTitle": 0,
      "ClinchedDivisionTitle": 0,
      "ClinchedPlayoffBirth": 0,
      "EliminatedConference": 0,
      "EliminatedDivision": 0,
      "AheadAtHalf": "26-8 ",
      "BehindAtHalf": "13-30",
      "TiedAtHalf": "1-4  ",
      "AheadAtThird": "29-11",
      "BehindAtThird": "8-30 ",
      "TiedAtThird": "3-1  ",
      "Score100PTS": "40-40",
      "OppScore100PTS": "33-42",
      "OppOver500": "23-28",
      "LeadInFGPCT": "30-10",
      "LeadInReb": "23-9 ",
      "FewerTurnovers": "33-31",
      "PointsPG": 117.5,
      "OppPointsPG": 116.4,
      "DiffPointsPG": 1.1,
      "vsEast": "15-15",
      "vsAtlantic": "6-4",
      "vsCentral": "5-5",
      "vsSoutheast": "4-6",
      "vsWest": "25-27",
      "vsNorthwest": "9-7",
      "vsPacific": "6-12",
      "vsSouthwest": "10-8",
      "Jan": "9-5",
      "Feb": "4-7",
      "Mar": "10-7",
      "Apr": "2-2",
      "May": null,
      "Jun": null,
      "Jul": null,
      "Aug": null,
      "Sep": null,
      "Oct": "3-3",
      "Nov": "6-10",
      "Dec": "6-8",
      "PreAS": "28-29",
      "PostAS": "12-13"
    },
    {
      "LeagueID": "00",
      "SeasonID": "22022",
      "TeamID": 1610612741,
      "TeamCity": "Chicago",
      "TeamName": "Bulls",
      "Conference": "East",
      "ConferenceRecord": "27-25",
      "PlayoffRank": 10,
      "ClinchIndicator": "",
      "Division": "Central",
      "DivisionRecord": "7-9  ",
      "DivisionRank": 3,
      "WINS": 40,
      "LOSSES": 42,
      "WinPCT": 0.488,
      "LeagueRank": 0,
      "Record": "40-42",
      "HOME": "22-19",
      "ROAD": "18-23",
      "L10": "6-4  ",
      "Last10Home": "4-6  ",
      "Last10Road": "8-2  ",
      "OT": "3-4  ",
      "ThreePTSOrLess": "4-7  ",
      "TenPTSOrMore": "24-19",
      "LongHomeStreak": 3,
      "strLongHomeStreak": "W 3",
      "LongRoadStreak": 6,
      "strLongRoadStreak": "W 6",
      "LongWinStreak": 3,
      "LongLossStreak": 6,
      "CurrentHomeStreak": 1,
      "strCurrentHomeStreak": "W 1",
      "CurrentRoadStreak": 1,
      "strCurrentRoadStreak": "W 1",
      "CurrentStreak": 2,
      "strCurrentStreak": "W 2",
      "ConferenceGamesBack": 18.0,
      "DivisionGamesBack": 18.0,
      "ClinchedConferenceTitle": 0,
      "ClinchedDivisionTitle": 0,
      "ClinchedPlayoffBirth": 0,
      "EliminatedConference": 0,
      "EliminatedDivision": 0,
      "AheadAtHalf": "27-12",
      "BehindAtHalf": "12-29",
      "TiedAtHalf": "1-1  ",
      "AheadAtThird": "31-9 ",
      "BehindAtThird": "8-32 ",
      "TiedAtThird": "1-1  ",
      "Score100PTS": "40-31",
      "OppScore100PTS": "29-41",
      "OppOver500": "23-27",
      "LeadInFGPCT": "34-17",
      "LeadInReb": "25-7 ",
      "FewerTurnovers": "25-26",
      "PointsPG": 113.1,
      "OppPointsPG": 111.8,
      "DiffPointsPG": 1.3,
      "vsEast": "27-25",
      "vsAtlantic": "9-9",
      "vsCentral": "7-9",
      "vsSoutheast": "11-7",
      "vsWest": "13-17",
      "vsNorthwest": "6-4",
      "vsPacific": "2-8",
      "vsSouthwest": "5-5",
      "Jan": "7-7",
      "Feb": "5-7",
      "Mar": "9-6",
      "Apr": "3-2",
      "May": null,
      "Jun": null,
      "Jul": null,
      "Aug": null,
      "Sep": null,
      "Oct": "3-4",
      "Nov": "6-8",
      "Dec": "7-8",
      "PreAS": "26-33",
      "PostAS": "14-9"
    },
    {
      "LeagueID": "00",
      "SeasonID": "22022",
      "TeamID": 1610612742,
      "TeamCity": "Dallas",
      "TeamName": "Mavericks",
      "Conference": "West",
      "ConferenceRecord": "28-24",
      "PlayoffRank": 11,
      "ClinchIndicator": " - o",
      "Division": "Southwest",
      "DivisionRecord": "9-7  ",
      "DivisionRank": 3,
      "WINS": 38,
      "LOSSES": 44,
      "WinPCT": 0.463,
      "LeagueRank": 0,
      "Record": "38-44",
      "HOME": "23-18",
      "ROAD": "15-26",
      "L10": "2-8  ",
      "Last10Home": "3-7  ",
      "Last10Road": "3-7  ",
      "OT": "4-5  ",
      "ThreePTSOrLess": "8-12 ",
      "TenPTSOrMore": "11-12",
      "LongHomeStreak": 6,
      "strLongHomeStreak": "W 6",
      "LongRoadStreak": -6,
      "strLongRoadStreak": "L 6",
      "LongWinStreak": 7,
      "LongLossStreak": 4,
      "CurrentHomeStreak": -2,
      "strCurrentHomeStreak": "L 2",
      "CurrentRoadStreak": -3,
      "strCurrentRoadStreak": "L 3",
      "CurrentStreak": -2,
      "strCurrentStreak": "L 2",
      "ConferenceGamesBack": 15.0,
      "DivisionGamesBack": 13.0,
      "ClinchedConferenceTitle": 0,
      "ClinchedDivisionTitle": 0,
      "ClinchedPlayoffBirth": 0,
      "EliminatedConference": 1,
      "EliminatedDivision": 1,
      "AheadAtHalf": "26-14",
      "BehindAtHalf": "10-30",
      "TiedAtHalf": "2-0  ",
      "AheadAtThird": "29-11",
      "BehindAtThird": "8-32 ",
      "TiedAtThird": "1-1  ",
      "Score100PTS": "36-36",
      "OppScore100PTS": "32-42",
      "OppOver500": "21-25",
      "LeadInFGPCT": "24-9 ",
      "LeadInReb": "10-4 ",
      "FewerTurnovers": "20-22",
      "PointsPG": 114.2,
      "OppPointsPG": 114.1,
      "DiffPointsPG": 0.1,
      "vsEast": "10-20",
      "vsAtlantic": "6-4",
      "vsCentral": "2-8",
      "vsSoutheast": "2-8",
      "vsWest": "28-24",
      "vsNorthwest": "9-9",
      "vsPacific": "10-8",
      "vsSouthwest": "9-7",
      "Jan": "6-9",
      "Feb": "5-6",
      "Mar": "5-9",
      "Apr": "1-4",
      "May": null,
      "Jun": null,
      "Jul": null,
      "Aug": null,
      "Sep": null,
      "Oct": "3-3",
      "Nov": "7-7",
      "Dec": "11-6",
      "PreAS": "31-29",
      "PostAS": "7-15"
    },
    {
      "LeagueID": "00",
      "SeasonID": "22022",
      "TeamID": 1610612754,
      "TeamCity": "Indiana",
      "TeamName": "Pacers",
      "Conference": "East",
      "ConferenceRecord": "24-28",
      "PlayoffRank": 11,
      "ClinchIndicator": " - o",
      "Division": "Central",
      "DivisionRecord": "7-9  ",
      "DivisionRank": 4,
      "WINS": 35,
      "LOSSES": 47,
      "WinPCT": 0.427,
      "LeagueRank": 0,
      "Record": "35-47",
      "HOME": "20-21",
      "ROAD": "15-26",
      "L10": "3-7  ",
      "Last10Home": "3-7  ",
      "Last10Road": "5-5  ",
      "OT": "1-2  ",
      "ThreePTSOrLess": "8-7  ",
      "TenPTSOrMore": "9-25 ",
      "LongHomeStreak": 6,
      "strLongHomeStreak": "W 6",
      "LongRoadStreak": -11,
      "strLongRoadStreak": "L 11",
      "LongWinStreak": 5,
      "LongLossStreak": 7,
      "CurrentHomeStreak": -2,
      "strCurrentHomeStreak": "L 2",
      "CurrentRoadStreak": 1,
      "strCurrentRoadStreak": "W 1",
      "CurrentStreak": 1,
      "strCurrentStreak": "W 1",
      "ConferenceGamesBack": 23.0,
      "DivisionGamesBack": 23.0,
      "ClinchedConferenceTitle": 0,
      "ClinchedDivisionTitle": 0,
      "ClinchedPlayoffBirth": 0,
      "EliminatedConference": 1,
      "EliminatedDivision": 1,
      "AheadAtHalf": "21-13",
      "BehindAtHalf": "14-34",
      "TiedAtHalf": "0-0  ",
      "AheadAtThird": "23-9 ",
      "BehindAtThird": "9-36 ",
      "TiedAtThird": "3-2  ",
      "Score100PTS": "34-42",
      "OppScore100PTS": "32-46",
      "OppOver500": "16-29",
      "LeadInFGPCT": "26-10",
      "LeadInReb": "17-10",
      "FewerTurnovers": "18-22",
      "PointsPG": 116.3,
      "OppPointsPG": 119.5,
      "DiffPointsPG": -3.2,
      "vsEast": "24-28",
      "vsAtlantic": "7-11",
      "vsCentral": "7-9",
      "vsSoutheast": "10-8",
      "vsWest": "11-19",
      "vsNorthwest": "2-8",
      "vsPacific": "5-5",
      "vsSouthwest": "4-6",
      "Jan": "4-11",
      "Feb": "4-7",
      "Mar": "6-9",
      "Apr": "1-3",
      "May": null,
      "Jun": null,
      "Jul": null,
      "Aug": null,
      "Sep": null,
      "Oct": "3-5",
      "Nov": "9-4",
      "Dec": "8-8",
      "PreAS": "26-34",
      "PostAS": "9-13"
    },
    {
      "LeagueID": "00",
      "SeasonID": "22022",
      "TeamID": 1610612764,
      "TeamCity": "Washington",
      "TeamName": "Wizards",
      "Conference": "East",
      "ConferenceRecord": "21-31",
      "PlayoffRank": 12,
      "ClinchIndicator": " - o",
      "Division": "Southeast",
      "DivisionRecord": "8-8  ",
      "DivisionRank": 3,
      "WINS": 35,
      "LOSSES": 47,
      "WinPCT": 0.427,
      "LeagueRank": 0,
      "Record": "35-47",
      "HOME": "19-22",
      "ROAD": "16-25",
      "L10": "3-7  ",
      "Last10Home": "4-6  ",
      "Last10Road": "3-7  ",
      "OT": "1-2  ",
      "ThreePTSOrLess": "7-6  ",
      "TenPTSOrMore": "19-21",
      "LongHomeStreak": -4,
      "strLongHomeStreak": "L 4",
      "LongRoadStreak": -10,
      "strLongRoadStreak": "L 10",
      "LongWinStreak": 6,
      "LongLossStreak": 10,
      "CurrentHomeStreak": -1,
      "strCurrentHomeStreak": "L 1",
      "CurrentRoadStreak": -6,
      "strCurrentRoadStreak": "L 6",
      "CurrentStreak": -1,
      "strCurrentStreak": "L 1",
      "ConferenceGamesBack": 23.0,
      "DivisionGamesBack": 9.0,
      "ClinchedConferenceTitle": 0,
      "ClinchedDivisionTitle": 0,
      "ClinchedPlayoffBirth": 0,
      "EliminatedConference": 1,
      "EliminatedDivision": 1,
      "AheadAtHalf": "26-14",
      "BehindAtHalf": "8-31 ",
      "TiedAtHalf": "1-2  ",
      "AheadAtThird": "30-8 ",
      "BehindAtThird": "5-37 ",
      "TiedAtThird": "0-2  ",
      "Score100PTS": "35-39",
      "OppScore100PTS": "30-47",
      "OppOver500": "19-27",
      "LeadInFGPCT": "31-11",
      "LeadInReb": "26-16",
      "FewerTurnovers": "10-16",
      "PointsPG": 113.2,
      "OppPointsPG": 114.4,
      "DiffPointsPG": -1.2,
      "vsEast": "21-31",
      "vsAtlantic": "5-13",
      "vsCentral": "8-10",
      "vsSoutheast": "8-8",
      "vsWest": "14-16",
      "vsNorthwest": "4-6",
      "vsPacific": "3-7",
      "vsSouthwest": "7-3",
      "Jan": "8-5",
      "Feb": "5-6",
      "Mar": "5-11",
      "Apr": "1-4",
      "May": null,
      "Jun": null,
      "Jul": null,
      "Aug": null,
      "Sep": null,
      "Oct": "3-4",
      "Nov": "8-7",
      "Dec": "5-10",
      "PreAS": "28-30",
      "PostAS": "7-17"
    },
    {
      "LeagueID": "00",
      "SeasonID": "22022",
      "TeamID": 1610612762,
      "TeamCity": "Utah",
      "TeamName": "Jazz",
      "Conference": "West",
      "ConferenceRecord": "24-28",
      "PlayoffRank": 12,
      "ClinchIndicator": " - o",
      "Division": "Northwest",
      "DivisionRecord": "6-10 ",
      "DivisionRank": 4,
      "WINS": 37,
      "LOSSES": 45,
      "WinPCT": 0.451,
      "LeagueRank": 0,
      "Record": "37-45",
      "HOME": "23-18",
      "ROAD": "14-27",
      "L10": "2-8  ",
      "Last10Home": "4-6  ",
      "Last10Road": "3-7  ",
      "OT": "4-1  ",
      "ThreePTSOrLess": "10-8 ",
      "TenPTSOrMore": "13-16",
      "LongHomeStreak": 5,
      "strLongHomeStreak": "W 5",
      "LongRoadStreak": -6,
      "strLongRoadStreak": "L 6",
      "LongWinStreak": 4,
      "LongLossStreak": 5,
      "CurrentHomeStreak": 1,
      "strCurrentHomeStreak": "W 1",
      "CurrentRoadStreak": -3,
      "strCurrentRoadStreak": "L 3",
      "CurrentStreak": -1,
      "strCurrentStreak": "L 1",
      "ConferenceGamesBack": 16.0,
      "DivisionGamesBack": 16.0,
      "ClinchedConferenceTitle": 0,
      "ClinchedDivisionTitle": 0,
      "ClinchedPlayoffBirth": 0,
      "EliminatedConference": 1,
      "EliminatedDivision": 1,
      "AheadAtHalf": "26-9 ",
      "BehindAtHalf": "10-35",
      "TiedAtHalf": "1-1  ",
      "AheadAtThird": "27-9 ",
      "BehindAtThird": "8-33 ",
      "TiedAtThird": "2-3  ",
      "Score100PTS": "37-40",
      "OppScore100PTS": "37-45",
      "OppOver500": "21-30",
      "LeadInFGPCT": "25-15",
      "LeadInReb": "24-23",
      "FewerTurnovers": "11-13",
      "PointsPG": 117.1,
      "OppPointsPG": 118.0,
      "DiffPointsPG": -0.9,
      "vsEast": "13-17",
      "vsAtlantic": "3-7",
      "vsCentral": "4-6",
      "vsSoutheast": "6-4",
      "vsWest": "24-28",
      "vsNorthwest": "6-10",
      "vsPacific": "8-10",
      "vsSouthwest": "10-8",
      "Jan": "7-6",
      "Feb": "5-6",
      "Mar": "5-9",
      "Apr": "1-4",
      "May": null,
      "Jun": null,
      "Jul": null,
      "Aug": null,
      "Sep": null,
      "Oct": "6-2",
      "Nov": "7-9",
      "Dec": "6-9",
      "PreAS": "29-31",
      "PostAS": "8-14"
    },
    {
      "LeagueID": "00",
      "SeasonID": "22022",
      "TeamID": 1610612757,
      "TeamCity": "Portland",
      "TeamName": "Trail Blazers",
      "Conference": "West",
      "ConferenceRecord": "23-29",
      "PlayoffRank": 13,
      "ClinchIndicator": " - o",
      "Division": "Northwest",
      "DivisionRecord": "7-9  ",
      "DivisionRank": 5,
      "WINS": 33,
      "LOSSES": 49,
      "WinPCT": 0.402,
      "LeagueRank": 0,
      "Record": "33-49",
      "HOME": "17-24",
      "ROAD": "16-25",
      "L10": "1-9  ",
      "Last10Home": "0-10 ",
      "Last10Road": "4-6  ",
      "OT": "2-0  ",
      "ThreePTSOrLess": "8-7  ",
      "TenPTSOrMore": "18-28",
      "LongHomeStreak": -10,
      "strLongHomeStreak": "L 10",
      "LongRoadStreak": -8,
      "strLongRoadStreak": "L 8",
      "LongWinStreak": 4,
      "LongLossStreak": 6,
      "CurrentHomeStreak": -10,
      "strCurrentHomeStreak": "L 10",
      "CurrentRoadStreak": -3,
      "strCurrentRoadStreak": "L 3",
      "CurrentStreak": -4,
      "strCurrentStreak": "L 4",
      "ConferenceGamesBack": 20.0,
      "DivisionGamesBack": 20.0,
      "ClinchedConferenceTitle": 0,
      "ClinchedDivisionTitle": 0,
      "ClinchedPlayoffBirth": 0,
      "EliminatedConference": 1,
      "EliminatedDivision": 1,
      "AheadAtHalf": "21-14",
      "BehindAtHalf": "11-34",
      "TiedAtHalf": "1-1  ",
      "AheadAtThird": "25-11",
      "BehindAtThird": "6-36 ",
      "TiedAtThird": "2-2  ",
      "Score100PTS": "33-38",
      "OppScore100PTS": "30-49",
      "OppOver500": "17-30",
      "LeadInFGPCT": "25-12",
      "LeadInReb": "21-15",
      "FewerTurnovers": "14-17",
      "PointsPG": 113.4,
      "OppPointsPG": 117.4,
      "DiffPointsPG": -4.0,
      "vsEast": "10-20",
      "vsAtlantic": "1-9",
      "vsCentral": "3-7",
      "vsSoutheast": "6-4",
      "vsWest": "23-29",
      "vsNorthwest": "7-9",
      "vsPacific": "6-12",
      "vsSouthwest": "10-8",
      "Jan": "6-9",
      "Feb": "5-6",
      "Mar": "3-13",
      "Apr": "1-4",
      "May": null,
      "Jun": null,
      "Jul": null,
      "Aug": null,
      "Sep": null,
      "Oct": "5-1",
      "Nov": "6-10",
      "Dec": "7-6",
      "PreAS": "28-30",
      "PostAS": "5-19"
    },
    {
      "LeagueID": "00",
      "SeasonID": "22022",
      "TeamID": 1610612753,
      "TeamCity": "Orlando",
      "TeamName": "Magic",
      "Conference": "East",
      "ConferenceRecord": "20-32",
      "PlayoffRank": 13,
      "ClinchIndicator": " - o",
      "Division": "Southeast",
      "DivisionRecord": "7-9  ",
      "DivisionRank": 4,
      "WINS": 34,
      "LOSSES": 48,
      "WinPCT": 0.415,
      "LeagueRank": 0,
      "Record": "34-48",
      "HOME": "20-21",
      "ROAD": "14-27",
      "L10": "5-5  ",
      "Last10Home": "5-5  ",
      "Last10Road": "3-7  ",
      "OT": "2-2  ",
      "ThreePTSOrLess": "5-6  ",
      "TenPTSOrMore": "16-24",
      "LongHomeStreak": -6,
      "strLongHomeStreak": "L 6",
      "LongRoadStreak": -6,
      "strLongRoadStreak": "L 6",
      "LongWinStreak": 6,
      "LongLossStreak": 9,
      "CurrentHomeStreak": -2,
      "strCurrentHomeStreak": "L 2",
      "CurrentRoadStreak": -2,
      "strCurrentRoadStreak": "L 2",
      "CurrentStreak": -4,
      "strCurrentStreak": "L 4",
      "ConferenceGamesBack": 24.0,
      "DivisionGamesBack": 10.0,
      "ClinchedConferenceTitle": 0,
      "ClinchedDivisionTitle": 0,
      "ClinchedPlayoffBirth": 0,
      "EliminatedConference": 1,
      "EliminatedDivision": 1,
      "AheadAtHalf": "25-11",
      "BehindAtHalf": "7-35 ",
      "TiedAtHalf": "2-2  ",
      "AheadAtThird": "24-6 ",
      "BehindAtThird": "9-41 ",
      "TiedAtThird": "1-1  ",
      "Score100PTS": "32-40",
      "OppScore100PTS": "26-48",
      "OppOver500": "19-30",
      "LeadInFGPCT": "30-11",
      "LeadInReb": "25-17",
      "FewerTurnovers": "15-23",
      "PointsPG": 111.4,
      "OppPointsPG": 114.0,
      "DiffPointsPG": -2.6,
      "vsEast": "20-32",
      "vsAtlantic": "8-10",
      "vsCentral": "5-13",
      "vsSoutheast": "7-9",
      "vsWest": "14-16",
      "vsNorthwest": "4-6",
      "vsPacific": "5-5",
      "vsSouthwest": "5-5",
      "Jan": "7-7",
      "Feb": "6-5",
      "Mar": "7-8",
      "Apr": "1-4",
      "May": null,
      "Jun": null,
      "Jul": null,
      "Aug": null,
      "Sep": null,
      "Oct": "1-6",
      "Nov": "4-11",
      "Dec": "8-7",
      "PreAS": "24-35",
      "PostAS": "10-13"
    },
    {
      "LeagueID": "00",
      "SeasonID": "22022",
      "TeamID": 1610612745,
      "TeamCity": "Houston",
      "TeamName": "Rockets",
      "Conference": "West",
      "ConferenceRecord": "12-40",
      "PlayoffRank": 14,
      "ClinchIndicator": " - o",
      "Division": "Southwest",
      "DivisionRecord": "4-12 ",
      "DivisionRank": 4,
      "WINS": 22,
      "LOSSES": 60,
      "WinPCT": 0.268,
      "LeagueRank": 0,
      "Record": "22-60",
      "HOME": "14-27",
      "ROAD": "8-33 ",
      "L10": "4-6  ",
      "Last10Home": "5-5  ",
      "Last10Road": "3-7  ",
      "OT": "1-1  ",
      "ThreePTSOrLess": "5-4  ",
      "TenPTSOrMore": "6-36 ",
      "LongHomeStreak": -10,
      "strLongHomeStreak": "L 10",
      "LongRoadStreak": -8,
      "strLongRoadStreak": "L 8",
      "LongWinStreak": 3,
      "LongLossStreak": 13,
      "CurrentHomeStreak": 1,
      "strCurrentHomeStreak": "W 1",
      "CurrentRoadStreak": 2,
      "strCurrentRoadStreak": "W 2",
      "CurrentStreak": 3,
      "strCurrentStreak": "W 3",
      "ConferenceGamesBack": 31.0,
      "DivisionGamesBack": 29.0,
      "ClinchedConferenceTitle": 0,
      "ClinchedDivisionTitle": 0,
      "ClinchedPlayoffBirth": 0,
      "EliminatedConference": 0,
      "EliminatedDivision": 0,
      "AheadAtHalf": "14-16",
      "BehindAtHalf": "7-44 ",
      "TiedAtHalf": "1-0  ",
      "AheadAtThird": "15-12",
      "BehindAtThird": "7-48 ",
      "TiedAtThird": "0-0  ",
      "Score100PTS": "21-49",
      "OppScore100PTS": "19-57",
      "OppOver500": "10-38",
      "LeadInFGPCT": "14-14",
      "LeadInReb": "19-34",
      "FewerTurnovers": "6-10 ",
      "PointsPG": 110.7,
      "OppPointsPG": 118.6,
      "DiffPointsPG": -7.9,
      "vsEast": "10-20",
      "vsAtlantic": "2-8",
      "vsCentral": "4-6",
      "vsSoutheast": "4-6",
      "vsWest": "12-40",
      "vsNorthwest": "5-13",
      "vsPacific": "3-15",
      "vsSouthwest": "4-12",
      "Jan": "2-12",
      "Feb": "1-10",
      "Mar": "6-11",
      "Apr": "3-1",
      "May": null,
      "Jun": null,
      "Jul": null,
      "Aug": null,
      "Sep": null,
      "Oct": "1-7",
      "Nov": "4-9",
      "Dec": "5-10",
      "PreAS": "13-45",
      "PostAS": "9-15"
    },
    {
      "LeagueID": "00",
      "SeasonID": "22022",
      "TeamID": 1610612766,
      "TeamCity": "Charlotte",
      "TeamName": "Hornets",
      "Conference": "East",
      "ConferenceRecord": "15-37",
      "PlayoffRank": 14,
      "ClinchIndicator": " - o",
      "Division": "Southeast",
      "DivisionRecord": "7-9  ",
      "DivisionRank": 5,
      "WINS": 27,
      "LOSSES": 55,
      "WinPCT": 0.329,
      "LeagueRank": 0,
      "Record": "27-55",
      "HOME": "13-28",
      "ROAD": "14-27",
      "L10": "5-5  ",
      "Last10Home": "2-8  ",
      "Last10Road": "6-4  ",
      "OT": "1-4  ",
      "ThreePTSOrLess": "3-3  ",
      "TenPTSOrMore": "8-35 ",
      "LongHomeStreak": -6,
      "strLongHomeStreak": "L 6",
      "LongRoadStreak": -7,
      "strLongRoadStreak": "L 7",
      "LongWinStreak": 5,
      "LongLossStreak": 8,
      "CurrentHomeStreak": -4,
      "strCurrentHomeStreak": "L 4",
      "CurrentRoadStreak": 3,
      "strCurrentRoadStreak": "W 3",
      "CurrentStreak": 1,
      "strCurrentStreak": "W 1",
      "ConferenceGamesBack": 31.0,
      "DivisionGamesBack": 17.0,
      "ClinchedConferenceTitle": 0,
      "ClinchedDivisionTitle": 0,
      "ClinchedPlayoffBirth": 0,
      "EliminatedConference": 1,
      "EliminatedDivision": 1,
      "AheadAtHalf": "15-8 ",
      "BehindAtHalf": "11-45",
      "TiedAtHalf": "1-2  ",
      "AheadAtThird": "18-6 ",
      "BehindAtThird": "9-48 ",
      "TiedAtThird": "0-1  ",
      "Score100PTS": "27-42",
      "OppScore100PTS": "25-54",
      "OppOver500": "15-31",
      "LeadInFGPCT": "21-7 ",
      "LeadInReb": "16-17",
      "FewerTurnovers": "12-30",
      "PointsPG": 111.0,
      "OppPointsPG": 117.2,
      "DiffPointsPG": -6.2,
      "vsEast": "15-37",
      "vsAtlantic": "2-16",
      "vsCentral": "6-12",
      "vsSoutheast": "7-9",
      "vsWest": "12-18",
      "vsNorthwest": "4-6",
      "vsPacific": "3-7",
      "vsSouthwest": "5-5",
      "Jan": "5-10",
      "Feb": "5-6",
      "Mar": "6-9",
      "Apr": "1-3",
      "May": null,
      "Jun": null,
      "Jul": null,
      "Aug": null,
      "Sep": null,
      "Oct": "3-4",
      "Nov": "3-11",
      "Dec": "4-12",
      "PreAS": "17-43",
      "PostAS": "10-12"
    },
    {
      "LeagueID": "00",
      "SeasonID": "22022",
      "TeamID": 1610612759,
      "TeamCity": "San Antonio",
      "TeamName": "Spurs",
      "Conference": "West",
      "ConferenceRecord": "10-42",
      "PlayoffRank": 15,
      "ClinchIndicator": " - o",
      "Division": "Southwest",
      "DivisionRecord": "3-13 ",
      "DivisionRank": 5,
      "WINS": 22,
      "LOSSES": 60,
      "WinPCT": 0.268,
      "LeagueRank": 0,
      "Record": "22-60",
      "HOME": "14-27",
      "ROAD": "8-33 ",
      "L10": "3-7  ",
      "Last10Home": "4-6  ",
      "Last10Road": "3-7  ",
      "OT": "1-5  ",
      "ThreePTSOrLess": "3-3  ",
      "TenPTSOrMore": "6-42 ",
      "LongHomeStreak": -5,
      "strLongHomeStreak": "L 5",
      "LongRoadStreak": -18,
      "strLongRoadStreak": "L 18",
      "LongWinStreak": 3,
      "LongLossStreak": 16,
      "CurrentHomeStreak": -1,
      "strCurrentHomeStreak": "L 1",
      "CurrentRoadStreak": 1,
      "strCurrentRoadStreak": "W 1",
      "CurrentStreak": 1,
      "strCurrentStreak": "W 1",
      "ConferenceGamesBack": 31.0,
      "DivisionGamesBack": 29.0,
      "ClinchedConferenceTitle": 0,
      "ClinchedDivisionTitle": 0,
      "ClinchedPlayoffBirth": 0,
      "EliminatedConference": 0,
      "EliminatedDivision": 0,
      "AheadAtHalf": "17-11",
      "BehindAtHalf": "4-47 ",
      "TiedAtHalf": "1-2  ",
      "AheadAtThird": "18-8 ",
      "BehindAtThird": "3-52 ",
      "TiedAtThird": "1-0  ",
      "Score100PTS": "22-48",
      "OppScore100PTS": "17-60",
      "OppOver500": "12-36",
      "LeadInFGPCT": "19-3 ",
      "LeadInReb": "15-17",
      "FewerTurnovers": "5-25 ",
      "PointsPG": 113.0,
      "OppPointsPG": 123.1,
      "DiffPointsPG": -10.0,
      "vsEast": "12-18",
      "vsAtlantic": "3-7",
      "vsCentral": "6-4",
      "vsSoutheast": "3-7",
      "vsWest": "10-42",
      "vsNorthwest": "6-12",
      "vsPacific": "1-17",
      "vsSouthwest": "3-13",
      "Jan": "2-13",
      "Feb": "1-10",
      "Mar": "4-11",
      "Apr": "3-2",
      "May": null,
      "Jun": null,
      "Jul": null,
      "Aug": null,
      "Sep": null,
      "Oct": "5-2",
      "Nov": "1-14",
      "Dec": "6-8",
      "PreAS": "14-45",
      "PostAS": "8-15"
    },
    {
      "LeagueID": "00",
      "SeasonID": "22022",
      "TeamID": 1610612765,
      "TeamCity": "Detroit",
      "TeamName": "Pistons",
      "Conference": "East",
      "ConferenceRecord": "8-44 ",
      "PlayoffRank": 15,
      "ClinchIndicator": " - o",
      "Division": "Central",
      "DivisionRecord": "2-14 ",
      "DivisionRank": 5,
      "WINS": 17,
      "LOSSES": 65,
      "WinPCT": 0.207,
      "LeagueRank": 0,
      "Record": "17-65",
      "HOME": "9-32 ",
      "ROAD": "8-33 ",
      "L10": "1-9  ",
      "Last10Home": "1-9  ",
      "Last10Road": "1-9  ",
      "OT": "3-1  ",
      "ThreePTSOrLess": "2-8  ",
      "TenPTSOrMore": "6-37 ",
      "LongHomeStreak": -6,
      "strLongHomeStreak": "L 6",
      "LongRoadStreak": -13,
      "strLongRoadStreak": "L 13",
      "LongWinStreak": 2,
      "LongLossStreak": 11,
      "CurrentHomeStreak": -5,
      "strCurrentHomeStreak": "L 5",
      "CurrentRoadStreak": -1,
      "strCurrentRoadStreak": "L 1",
      "CurrentStreak": -1,
      "strCurrentStreak": "L 1",
      "ConferenceGamesBack": 41.0,
      "DivisionGamesBack": 41.0,
      "ClinchedConferenceTitle": 0,
      "ClinchedDivisionTitle": 0,
      "ClinchedPlayoffBirth": 0,
      "EliminatedConference": 1,
      "EliminatedDivision": 1,
      "AheadAtHalf": "12-14",
      "BehindAtHalf": "5-50 ",
      "TiedAtHalf": "0-1  ",
      "AheadAtThird": "14-6 ",
      "BehindAtThird": "2-55 ",
      "TiedAtThird": "1-4  ",
      "Score100PTS": "17-51",
      "OppScore100PTS": "15-63",
      "OppOver500": "7-39 ",
      "LeadInFGPCT": "14-12",
      "LeadInReb": "11-14",
      "FewerTurnovers": "11-18",
      "PointsPG": 110.3,
      "OppPointsPG": 118.5,
      "DiffPointsPG": -8.2,
      "vsEast": "8-44",
      "vsAtlantic": "1-17",
      "vsCentral": "2-14",
      "vsSoutheast": "5-13",
      "vsWest": "9-21",
      "vsNorthwest": "5-5",
      "vsPacific": "2-8",
      "vsSouthwest": "2-8",
      "Jan": "3-10",
      "Feb": "2-8",
      "Mar": "1-14",
      "Apr": "1-4",
      "May": null,
      "Jun": null,
      "Jul": null,
      "Aug": null,
      "Sep": null,
      "Oct": "2-6",
      "Nov": "3-12",
      "Dec": "5-11",
      "PreAS": "15-44",
      "PostAS": "2-21"
    }
  ]